/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/K8bTlkLzir6
 */
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"

export function TestCard() {
  return (
    <Card>
      <CardHeader>
        <div className="flex items-center">
          <div>
            <CardTitle>MCQ Management System</CardTitle>
            <CardDescription>Multiple Choice Questions</CardDescription>
          </div>
          <Button className="ml-auto rounded-full w-8 h-8 flex items-center" size="md" variant="ghost">
            <BookmarkIcon className="w-4 h-4" />
            <span className="sr-only">Bookmark</span>
          </Button>
        </div>
      </CardHeader>
      <CardContent>
        <div className="flex items-center space-x-4">
          <div className="text-sm font-medium">Submitted</div>
          <div className="text-sm font-medium">Not submitted</div>
          <div className="text-sm font-medium">Average score</div>
        </div>
        <div className="flex items-center space-x-4">
          <div className="text-2xl font-semibold">25</div>
          <div className="text-2xl font-semibold">10</div>
          <div className="text-2xl font-semibold">75%</div>
        </div>
        <Button className="mt-4 w-full">Take the Test</Button>
      </CardContent>
    </Card>
  )
}


function BookmarkIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m19 21-7-4-7 4V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v16z" />
    </svg>
  )
}
